package com.xccu.web.api.bootapi;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@RestController
@MapperScan("com.xccu.web.api.bootapi.mapper")
@SpringBootApplication
public class BootApiApplication {

    public static void main(String[] args) {
        SpringApplication.run(BootApiApplication.class, args);
    }

    //利用@RequestMapping配置url和方法之间的映射
    @RequestMapping("/hello")
    public String hello() {
        return "Hello Weslie!";
    }

}
